/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TelemetryData {
  processed: number
  latencies: Array<number>
}
export declare function init(): void
export declare class NapiPipeline {
  constructor()
  ingest(buffer: Buffer): boolean
  pollTelemetry(): TelemetryData
  pollNext(callback: (...args: any[]) => any): boolean
}
