// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A single market tick event representing a trade or quote update.
 * This is the fundamental unit of data transported through the ring buffer.
 */
export class Event {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Event {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEvent(bb:flatbuffers.ByteBuffer, obj?:Event):Event {
  return (obj || new Event()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEvent(bb:flatbuffers.ByteBuffer, obj?:Event):Event {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Event()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Nanosecond-precision Unix epoch timestamp.
 * Using int64 instead of uint64 for cross-language compatibility.
 */
timestampNs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Ticker symbol identifier (e.g., "AAPL", "BTC-USD").
 */
symbol():string|null
symbol(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
symbol(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Execution price in the quote currency.
 * Using float64 (double) for sufficient precision in financial calculations.
 */
price():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Trade volume (number of shares/contracts/units).
 */
volume():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Sequential event ID for ordering verification in tests.
 * Critical for validating SPSC ordering guarantees.
 */
sequenceId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startEvent(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTimestampNs(builder:flatbuffers.Builder, timestampNs:bigint) {
  builder.addFieldInt64(0, timestampNs, BigInt('0'));
}

static addSymbol(builder:flatbuffers.Builder, symbolOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, symbolOffset, 0);
}

static addPrice(builder:flatbuffers.Builder, price:number) {
  builder.addFieldFloat64(2, price, 0.0);
}

static addVolume(builder:flatbuffers.Builder, volume:bigint) {
  builder.addFieldInt64(3, volume, BigInt('0'));
}

static addSequenceId(builder:flatbuffers.Builder, sequenceId:bigint) {
  builder.addFieldInt64(4, sequenceId, BigInt('0'));
}

static endEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createEvent(builder:flatbuffers.Builder, timestampNs:bigint, symbolOffset:flatbuffers.Offset, price:number, volume:bigint, sequenceId:bigint):flatbuffers.Offset {
  Event.startEvent(builder);
  Event.addTimestampNs(builder, timestampNs);
  Event.addSymbol(builder, symbolOffset);
  Event.addPrice(builder, price);
  Event.addVolume(builder, volume);
  Event.addSequenceId(builder, sequenceId);
  return Event.endEvent(builder);
}
}
