"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Event = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
const flatbuffers = __importStar(require("flatbuffers"));
/**
 * A single market tick event representing a trade or quote update.
 * This is the fundamental unit of data transported through the ring buffer.
 */
class Event {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsEvent(bb, obj) {
        return (obj || new Event()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsEvent(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Event()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    /**
     * Nanosecond-precision Unix epoch timestamp.
     * Using int64 instead of uint64 for cross-language compatibility.
     */
    timestampNs() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt64(this.bb_pos + offset) : BigInt('0');
    }
    symbol(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    /**
     * Execution price in the quote currency.
     * Using float64 (double) for sufficient precision in financial calculations.
     */
    price() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    /**
     * Trade volume (number of shares/contracts/units).
     */
    volume() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readUint64(this.bb_pos + offset) : BigInt('0');
    }
    /**
     * Sequential event ID for ordering verification in tests.
     * Critical for validating SPSC ordering guarantees.
     */
    sequenceId() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readUint64(this.bb_pos + offset) : BigInt('0');
    }
    static startEvent(builder) {
        builder.startObject(5);
    }
    static addTimestampNs(builder, timestampNs) {
        builder.addFieldInt64(0, timestampNs, BigInt('0'));
    }
    static addSymbol(builder, symbolOffset) {
        builder.addFieldOffset(1, symbolOffset, 0);
    }
    static addPrice(builder, price) {
        builder.addFieldFloat64(2, price, 0.0);
    }
    static addVolume(builder, volume) {
        builder.addFieldInt64(3, volume, BigInt('0'));
    }
    static addSequenceId(builder, sequenceId) {
        builder.addFieldInt64(4, sequenceId, BigInt('0'));
    }
    static endEvent(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishEventBuffer(builder, offset) {
        builder.finish(offset);
    }
    static finishSizePrefixedEventBuffer(builder, offset) {
        builder.finish(offset, undefined, true);
    }
    static createEvent(builder, timestampNs, symbolOffset, price, volume, sequenceId) {
        Event.startEvent(builder);
        Event.addTimestampNs(builder, timestampNs);
        Event.addSymbol(builder, symbolOffset);
        Event.addPrice(builder, price);
        Event.addVolume(builder, volume);
        Event.addSequenceId(builder, sequenceId);
        return Event.endEvent(builder);
    }
}
exports.Event = Event;
