"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Event = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var event_js_1 = require("./event/event.js");
Object.defineProperty(exports, "Event", { enumerable: true, get: function () { return event_js_1.Event; } });
